name: Upload Release Asset
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  linux-windows-build:
    name: Linux & Windows Build
    runs-on: ubuntu-latest
    steps:

      - name: Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16beta1
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Make Linux
        run: export PATH=/home/runner/go/bin/:$PATH && make linux

      - name: Make Windows
        run: export PATH=/home/runner/go/bin/:$PATH && make windows

      - name: Package
        run: make zip_exe

      - name: Windows Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: ./dist/ch-*

      - name: Linux Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: ./dist/ch-*

  macos-build:
    name: MacOS Build
    runs-on: macos-latest
    steps:

      - name: Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16beta1
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Make Darwin
        run: export PATH=/Users/runner/go/bin/:$PATH && make macos

      - name: Package
        run: make zip_exe

      - name: MacOS Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macos
          path: ./dist/ch-*

  tagged-release:

    needs: [linux-windows-build, macos-build]

    name: "Tagged Release"
    runs-on: ubuntu-latest

    steps:
      - run: mkdir -p ./artifacts && mkdir -p ./release
      - uses: actions/download-artifact@v2
        with:
          path: ./artifacts

      - name: Package Linux
        run: |
          zip -j ./release/ch-linux-amd64.zip ./artifacts/ch-linux-amd64
          zip -j ./release/ch-linux-arm64.zip ./artifacts/ch-linux-arm64

      - name: Package Windows
        run: |
          zip -j ./release/ch-windows-amd64.zip ./artifacts/ch-windows-amd64

      - name: Package MacOS
        run: |
          zip -j ./release/ch-darwin-amd64.zip ./artifacts/ch-darwin-amd64
          zip -j ./release/ch-darwin-arm64.zip ./artifacts/ch-darwin-arm64

      - name: Publish Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./release/*.zip
