name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  linux-windows-build:
    name: Linux & Windows Build
    runs-on: ubuntu-latest
    steps:

      - name: Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16beta1
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Make Linux
        run: export PATH=/home/runner/go/bin/:$PATH && make linux

      - name: Make Windows
        run: export PATH=/home/runner/go/bin/:$PATH && make windows

      - name: Package
        run: make zip_exe


  macos-build:
    name: MacOS Build
    runs-on: macos-latest
    steps:

      - name: Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16beta1
        id: go

      - name: Make Darwin
        run: export PATH=/Users/runner/go/bin/:$PATH && make macos

      - name: Package
        run: make zip_exe
