name: Unit Test

on: push

jobs:
  unit-test:
    # name of job
    name: Unit Test Modules

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.5'

      - name: Run util tests
        uses: cd cmd/util && go test -v
